Repository mybatis/spring, pull requests merged in 2020-06, with the labels that each got.

#477 Upgrade to spring 5.1.15 and spring-batch 4.1.4 on Travis CI
  .travis.yml
Labels: dependencies

#482 Apply mybatis-parent 32-SNAPSHOT for resolving maven-bundle-plugin error on Travis CI
  .travis.yml
  pom.xml
Labels: enhancement

#486 Change the method name to getPropertyValue
  src/main/java/org/mybatis/spring/mapper/MapperScannerConfigurer.java
Labels: polishing
