Repository mybatis/spring, pull requests merged in 2022-05, with the labels that each got.

#462 Introduce Spring's AliasFor declaration in MapperScan
  src/main/java/org/mybatis/spring/annotation/MapperScan.java
  src/main/java/org/mybatis/spring/annotation/MapperScannerRegistrar.java
Labels: enhancement, no backward compatibility

#671 Update document for 2.1
  README.md
  src/main/java/org/mybatis/spring/annotation/MapperScan.java
  src/site/es/markdown/index.md
  src/site/ja/markdown/index.md
  src/site/ko/markdown/index.md
  src/site/markdown/index.md
  src/site/zh/markdown/index.md
Labels: documentation

#675 Support JDK 18-ga and 19-ea on CI
  .github/workflows/ci.yaml
  .github/workflows/compatibility-check-spring6.yaml
  .github/workflows/coveralls.yaml
  .github/workflows/sonar.yaml
  .github/workflows/sonatype.yaml
  .github/workflows/support.yaml
Labels: enhancement

#676 Refine max-parallel on CI
  .github/workflows/ci.yaml
  .github/workflows/compatibility-check-spring6.yaml
  .github/workflows/support.yaml
Labels: enhancement

#661 Fix batch.md in site/ko.markdown
  src/site/ko/markdown/batch.md
Labels: documentation
